### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Ferada** [dancysoft/bittorrent#2]
Hi, I'd be interested in porting this to non-ACL implementations, so before I take a closer look, under what license is this code and could that be made sure by adding a note to the repository?

Also, would you accept patches to make this run on other CLs?

**Comment by dancysoft** [comment]
On Mon, Jan 19, 2015 at 1:42 PM, Olof-Joachim Frahm <
notifications@github.com> wrote:

> Hi, I'd be interested in porting this to non-ACL implementations, so
> before I take a closer look, under what license is this code and could that
> be made sure by adding a note to the repository?
>
I never thought I'd have cause to consider the license.  What's the best "I
give this to world" license these days?

Also, would you accept patches to make this run on other CLs?
>

Yes, although I reserve the right to request adjustments in design or
implementation before acceptance.  Fair?

**Comment by Ferada** [comment]
> I never thought I'd have cause to consider the license. What's the best "I give this to world" license these days?

A lot of projects use one of MIT, (probably two clause) BSD, or the [LLGPL](http://www.cliki.net/LLGPL), which is LGPL with some special wording for Lisp code.
Full GPL seems to be a bit rare at least in CL land.

> > Also, would you accept patches to make this run on other CLs?

> Yes, although I reserve the right to request adjustments in design or implementation before acceptance. Fair?

Sure, absolutely, it's your repository :)

**Comment by dancysoft** [comment]
LICENSE file added.

**Comment by Ferada** [comment]
Thank you for adding the license!
